import type { Node, Edge } from '@xyflow/react';
import { MarkerType } from '@xyflow/react';

export const nodes: Node[] = [
  { id: '101',
    type: 'custom',
    data: { label: '컴퓨터 프로그래밍 I', preRequisite: [], postRequisite: ['컴퓨터 프로그래밍 II'], tags: ['1'], displayMode: 1, isSelected: true },
    position: { x: 0, y: 0 },
  },
  {
    id: '102',
    type: 'custom',
    data: { label: '컴퓨터 프로그래밍 II', preRequisite: ['컴퓨터 프로그래밍 I'], postRequisite: ['자료구조'], tags: ['1'], displayMode: 1, isSelected: true },
    position: { x: 250, y: 0 },
  },
  {
    id: '111',
    type: 'custom',
    data: { label: '전산수학I', preRequisite: [], postRequisite: ['전산수학II'], tags: ['1'], displayMode: 1, isSelected: true },
    position: { x: 0, y: 100 },
  },
  {
    id: '112',
    type: 'custom',
    data: { label: '전산수학II', preRequisite: ['전산수학I'], postRequisite: [], tags: ['1'], displayMode: 1, isSelected: true },
    position: { x: 250, y: 100 },
  },
  {
    id: '213',
    type: 'custom',
    data: { label: '자료구조',  preRequisite: ['컴퓨터 프로그래밍 II'], postRequisite: ['알고리즘'], tags: ['2'], displayMode: 1, isSelected: true },
    position: { x: 500, y: 0 },
  },
  {
    id: '214',
    type: 'custom',
    data: { label: '알고리즘', preRequisite: ['자료구조'], postRequisite: [], tags: ['2'], displayMode: 1, isSelected: true },
    position: { x: 750, y: 0 },
  },
  {
    id: '221',
    type: 'custom',
    data: { label: '논리설계', preRequisite: [], postRequisite: ['컴퓨터구조'], tags: ['2'], displayMode: 1, isSelected: true },
    position: { x: 500, y: 100 },
  },
  {
    id: '222',
    type: 'custom',
    data: { label: '컴퓨터구조', preRequisite: ['논리설계'], postRequisite: ['운영체제', '컴퓨터시스템설계'], tags: ['2'], displayMode: 1, isSelected: true },
    position: { x: 750, y: 100 },
  },
  {
    id: '211',
    type: 'custom',
    data: { label: '이산수학', preRequisite: [], postRequisite: [], tags: ['2'], displayMode: 1, isSelected: true },
    position: { x: 500, y: 200 },
  },
  {
    id: '215',
    type: 'custom',
    data: { label: '계산이론', preRequisite: [], postRequisite: ['프로그래밍언어'], tags: ['2'], displayMode: 1, isSelected: true },
    position: { x: 500, y: 300 },
  },
  {
    id: '212',
    type: 'custom',
    data: { label: '프로그래밍언어', preRequisite: ['계산이론'], postRequisite: [], tags: ['2'], displayMode: 1, isSelected: true },
    position: { x: 750, y: 300 },
  },
  {
    id: '242',
    type: 'custom',
    data: { label: '데이터통신', preRequisite: [], postRequisite: ['컴퓨터네트워크'], tags: ['2'], displayMode: 1, isSelected: true },
    position: { x: 750, y: 400 },
  },
  {
    id: '281',
    type: 'custom',
    data: { label: '공학수학', preRequisite: [], postRequisite: [], tags: ['2'], displayMode: 1, isSelected: true },
    position: { x: 500, y: 500 },
  },
  {
    id: '284',
    type: 'custom',
    data: { label: '전자기학', preRequisite: [], postRequisite: [], tags: ['2'], displayMode: 1, isSelected: true },
    position: { x: 750, y: 500 },
  },
  {
    id: '361',
    type: 'custom',
    data: { label: '인공지능', preRequisite: [], postRequisite: ['기계학습'], tags: ['3'], displayMode: 1, isSelected: true },
    position: { x: 500, y: -100 },
  },
  {
    id: '362',
    type: 'custom',
    data: { label: '기계학습', preRequisite: ['인공지능'], postRequisite: ['딥러닝'], tags: ['3'], displayMode: 1, isSelected: true },
    position: { x: 750, y: -100 },
  },
  { id: '341',
    type: 'custom',
    data: { label: '운영체제', preRequisite: ['컴퓨터구조'], postRequisite: ['시스템프로그래밍'], tags: ['3'], displayMode: 1, isSelected: true },
    position: { x: 1000, y: 100 },
  },
  { id: '321',
    type: 'custom',
    data: { label: '컴퓨터시스템설계', preRequisite: ['컴퓨터구조'], postRequisite: [], tags: ['3'], displayMode: 1, isSelected: true },
    position: { x: 1000, y: 200 },
  },
  { id: '322',
    type: 'custom',
    data: { label: '시스템프로그래밍', preRequisite: ['운영체제'], postRequisite: [], tags: ['3'], displayMode: 1, isSelected: true },
    position: { x: 1250, y: 100 },
  },
  { id: '371',
    type: 'custom',
    data: { label: '데이터베이스', preRequisite: [], postRequisite: ['데이터베이스시스템'], tags: ['3'], displayMode: 1, isSelected: true },
    position: { x: 1000, y: 0 },
  },
  { id: '372',
    type: 'custom',
    data: { label: '데이터베이스시스템', preRequisite: ['데이터베이스'], postRequisite: [], tags: ['3'], displayMode: 1, isSelected: true },
    position: { x: 1250, y: 0 },
  },
  { id: '474',
    type: 'custom',
    data: { label: '딥러닝', preRequisite: ['기계학습'], postRequisite: [], tags: ['4'], displayMode: 1, isSelected: true },
    position: { x: 1250, y: -100 },
  },
  { id: '342',
    type: 'custom',
    data: { label: '컴퓨터네트워크', preRequisite: ['데이터통신'], postRequisite: [], tags: ['3'], displayMode: 1, isSelected: true },
    position: { x: 1250, y: 400 },
  },
  { id: '385',
    type: 'custom',
    data: { label: '신호및시스템', preRequisite: [], postRequisite: ['디지털신호처리'], tags: ['3'], displayMode: 1, isSelected: true },
    position: { x: 1000, y: 500 },
  },
  { id: '380',
    type: 'custom',
    data: { label: '디지털신호처리', preRequisite: ['신호및시스템'], postRequisite: [], tags: ['3'], displayMode: 1, isSelected: true },
    position: { x: 1250, y: 500 },
  },
  { id: '354',
    type: 'custom',
    data: { label: '정보보호', preRequisite: [], postRequisite: [], tags: ['3'], displayMode: 1, isSelected: true },
    position: { x: 1250, y: 300 },
  },
  { id: '331',
    type: 'custom',
    data: { label: '컴퓨터그래픽스', preRequisite: [], postRequisite: [], tags: ['3'], displayMode: 1, isSelected: true },
    position: { x: 1000, y: 600 },
  }
];

export const edges: Edge[] = [
  { id: '101->102', type: 'custom', source: '101', target: '102', markerEnd: { type: MarkerType.ArrowClosed } },
  { id: '102->213', type: 'custom', source: '102', target: '213', markerEnd: { type: MarkerType.ArrowClosed } },
  { id: '111->112', type: 'custom', source: '111', target: '112', markerEnd: { type: MarkerType.ArrowClosed } },
  { id: '213->214', type: 'custom', source: '213', target: '214', markerEnd: { type: MarkerType.ArrowClosed } },
  { id: '221->222', type: 'custom', source: '221', target: '222', markerEnd: { type: MarkerType.ArrowClosed } },
  { id: '215->212', type: 'custom', source: '215', target: '212', markerEnd: { type: MarkerType.ArrowClosed } },
  { id: '361->362', type: 'custom', source: '361', target: '362', markerEnd: { type: MarkerType.ArrowClosed } },
  { id: '222->341', type: 'custom', source: '222', target: '341', markerEnd: { type: MarkerType.ArrowClosed } },
  { id: '222->321', type: 'custom', source: '222', target: '321', markerEnd: { type: MarkerType.ArrowClosed } },
  { id: '341->322', type: 'custom', source: '341', target: '322', markerEnd: { type: MarkerType.ArrowClosed } },
  { id: '371->372', type: 'custom', source: '371', target: '372', markerEnd: { type: MarkerType.ArrowClosed } },
  { id: '362->474', type: 'custom', source: '362', target: '474', markerEnd: { type: MarkerType.ArrowClosed } },
  { id: '242->342', type: 'custom', source: '242', target: '342', markerEnd: { type: MarkerType.ArrowClosed } },
  { id: '385->380', type: 'custom', source: '385', target: '380', markerEnd: { type: MarkerType.ArrowClosed } },
];